### ISSUE TITLE
OAPI : #[salvo(schema(name = XXX))]  expects an identifier instead of a "string" literal

### ISSUE THREAD

**Issue by rxdiscovery** [salvo-rs/salvo#832] opened 2024-07-15 00:22 UTC
Hello,

**Describe the bug :**

An error now occurs in new versions of Salvo with OpenAPI :

```rust
use salvo::oapi::ToSchema;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, ToSchema)]
#[salvo(schema(name = "City"))]  //<-- `error: expected identifier`
pub struct CityDTO {
    #[salvo(schema(rename = "id"))]
    pub id: String,
    #[salvo(schema(rename = "name"))]
    pub name: String,
}
```
gives this error : 
`error: expected identifier`

but by using an **identifier** instead of a **string**, it works.

```rust
#[salvo(schema(name = City))]
```

Normally **name** must take a literal string as parameter instead of an identifier, otherwise it may be confused with variables in the code.

And the weirdest thing is that it works on some names and not others:

![Screenshot from 2024-07-15 01-45-13](https://github.com/user-attachments/assets/05f9632b-e2bd-4867-90d1-6f71f23f51d6)

it works for **LoginDTO** but not for **CityDTO** !!

**Salvo version : **
```toml
salvo = { version = "0.68.5", features = ["oapi", "jwt-auth", "compression"] }
salvo-oapi = "0.68.5"
```

**Comment by TheAwiteb** [comment] 2024-07-27 08:43
> it works for LoginDTO but not for CityDTO !!

I don't think it's a bug, because in the first one you're using `#[salvo(symbol(name = "LoginRequest"))]` while in the second one using `#[salvo(schema(name = "City"))]`. There is a diffrence between `symbol` and `schema`.

### Note
The `#[salvo(symbol(name = "LoginRequest"))]` will have no effect, because Salvo does not support it.

**Comment by rxdiscovery** [comment] 2024-07-27 16:35
> > it works for LoginDTO but not for CityDTO !!
> 
> I don't think it's a bug, because in the first one you're using `#[salvo(symbol(name = "LoginRequest"))]` while in the second one using `#[salvo(schema(name = "City"))]`. There is a diffrence between `symbol` and `schema`.
> ### Note
> 
> The `#[salvo(symbol(name = "LoginRequest"))]` will have no effect, because Salvo does not support it.

Thank you very much for your remarks, 

Is it normal that `#[salvo(schema(name = "City"))]` no longer accepts literal strings?

**Comment by TheAwiteb** [comment] 2024-07-28 06:28
> Is it normal that #[salvo(schema(name = "City"))] no longer accepts literal strings?

It was with [`#[salvo(schema(symbol = "..."))]`](https://github.com/salvo-rs/salvo/blob/5def49957065a54f2a39133b84f385a01e60aca9/crates/oapi/src/openapi/mod.rs#L1146) but not with `name`, as you can see [here](https://github.com/salvo-rs/salvo/commit/8504240ebdebbbdd3b69d3156b5688ce9ae16293#diff-198619ded4debe85996e8c24a3e66842d819cc497d0b0b6e4a24ff874897b49c).


Ultimately, Salvo is not stable yet, so you should expect changes like this.

**Comment by TheAwiteb** [comment] 2024-07-29 09:48
Should we close this issue? It's not a bug

cc: @rxdiscovery @chrislearn

**Comment by rxdiscovery** [comment] 2024-07-29 10:13
> Should we close this issue? It's not a bug
> 
> cc: @rxdiscovery @chrislearn

I think it should be kept open, “name” should take a literal string so as not to cause confusion with an already existing type/struct.

**Comment by TheAwiteb** [comment] 2024-07-29 10:37
> I think it should be kept open, “name” should take a literal string so as not to cause confusion with an already existing type/struct.

@chrislearn What do you think? will Salvo support this? if yes we should open this issue.

For me, I think we should not, I think using identifier only is better.

**Comment by chrislearn** [comment] 2024-08-06 07:09
I think this decision can be left to the users, as they may have different usage preferences.

**Closed** 2024-08-06 08:03 UTC
